# Generated by Django 3.0.8 on 2020-07-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200726_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Test')),
            ],
        ),
    ]
