# Generated by Django 3.0.8 on 2020-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wrong_answer',
            field=models.IntegerField(default=0),
        ),
    ]
