# Generated by Django 3.0.8 on 2020-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200808_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='test_id',
            new_name='test',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
